### Code

Code should follow the [tidyverse style](https://style.tidyverse.org/).
Particularly,

-   there should be spaces before and line breaks after each `+` when building a `ggplot`,
-   there should also be spaces before and line breaks after each `|>` in a data transformation pipeline,
-   code should be properly indented,
-   there should be spaces around `=` signs and spaces after commas.

Additionally, all code should be visible in the PDF output, i.e., should not run off the page on the PDF.
Long lines that run off the page should be split across multiple lines with line breaks.

### Plots

-   Plots should have an informative title and, if needed, also a subtitle.
-   Axes and legends should be labeled with both the variable name and its units (if applicable).
-   Careful consideration should be given to aesthetic choices.

### Workflow

Continuing to develop a sound workflow for reproducible data analysis is important as you complete the lab and other assignments in this course.

-   You should have at least 3 commits with meaningful commit messages by the end of the assignment.
-   Final versions of both your `.qmd` file and the rendered PDF should be pushed to GitHub.
