---
title: "Assignments and grading"
---

Your final course grade will be calculated as follows:

::: {.center-table}
| Category              | Percentage |
|-----------------------|------------|
| Lecture attendance    | 5%         |
| Labs                  | 8%         |
| Homework              | 12%        |
| Final project         | 15%        |
| Midterm exam 1        | 20%        |
| Midterm exam 2        | 20%        |
| Final exam            | 20%        |
:::

Your final letter grade will be determined based on these thresholds:

::: {.center-table}
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |
:::

::: callout-warning
These thresholds will not change, and they will be applied exactly. This means that the final grades will not be curved, and a 92.99, for example, will not be rounded up to an A.
:::


## Lecture attendance (5%)

After Drop/Add ends on Wednesday January 21, lecture attendance and participation will be tracked through in-class questions via Wooclap, which you can access on your laptop or phone. You will earn points for answering questions during lecture, and these points will contribute to your attendance and participation grade.

There are 22 lectures after Drop/Add ends. You must participate in Wooclap questions in at least 18 lectures to get full credit on this component. Otherwise your grade on this component will be calculated as the percentage of lectures you attended and participated, e.g., if you attend and participate in 19/22 lectures, you get the full 5% but if you attend and participate in 15/22 lectures, you get (15/22)5% = 3.41%.

## Labs (8%)

In the first few weeks of the semester, you will be randomly assigned to a team and work with your teammates on an exercise that is due at the end of the lab session. Once project teams are formed, you will work with that team on the lab exercises. You must be present in lab to complete the lab assignment. There is no way to make up for missing a lab.

You will submit your lab assignments by pushing your work to your GitHub repository for the lab and submitting the PDF output on Gradescope by the end of your lab session.

::: callout-note
## Grace
There will be eight graded labs in total. The lowest two lab grades will be dropped at the end of the semester, which means you can miss up to two lab sessions with no penalty.
:::

## Homework (12%)

You will complete homework assignments individually. You may start working on your homeowork assignment during your lab session, once you complete your lab exercise, but you will need to finish it outside of class. Your homework will be comprised of some practice exercises where you can get immediate feedback from AI tools designed for this course and some graded exercises.

You will submit your homework assignments by pushing your work to your GitHub repository for the homework and submitting the PDF output on Gradescope by 11:59pm on Wednesdays.

::: callout-note
## Grace
There will be eight graded homework assignments in total. The lowest homework grade will be dropped at the end of the semester, which means you can miss one homework assignment with no penalty.
:::

## Project (15%)

The project aims to apply what you’ve learned throughout the semester to analyze an interesting data-driven research question. The project will be completed in teams, and each team will present their work during a lab session in the latter part of the semester. The write-up will be due on the same day.

More information about the project will be provided during the semester.

::: callout-warning
You cannot pass this course if you have not completed the project.
:::

## Midterm Exams (20% each)

There will be two midterm exams, each with two components:

-   **In-class** (70% of the grade): sit-down, in-person, "pencil-and-paper," with no technology, and with no outside resources apart from a note sheet that you and only you have prepared (both sides of a single 8.5" x 11" piece of paper);
-   **Take-home** (30% of the grade): each in-class midterm exam takes place during lecture on Wednesday. After that, you have the following weekend to complete the take-home exam. This will consist of a data analysis in R, and submission will be identical to our usual homeworks (Quarto \> PDF \> Gradescope). The take-home portion of the midterms is completely open resource, but the citation policies of the course still apply, and you are forbidden from discussing the exam with your peers in any way.

Unless we indicate otherwise, you should assume that all course content and materials (videos, readings, lectures, labs, AEs, etc) are testable.

::: callout-warning
## Missing midterms
See the [course schedule](https://sta199-s26.github.io/) for dates and times of the exams. Exam dates cannot be changed and no make-up exams will be given. 

- If you already know that you cannot take the exams on these dates, you should drop this class;
- If you miss Exam 1 or 2 due to an illness or similar documented with a Dean’s Excuse, your final exam score will replace the missed exam score.
:::

## Final Exam (20%)

On Tuesday April 29 we have our final exam from 9AM ET to 12PM ET. This exam will be cumulative, and it will have the same format as the in-class components of the midterm exams. The final exam does not have a take-home portion.

::: callout-warning
## Missing the final
See [here](https://trinity.duke.edu/undergraduate/academic-policies/final-exams-scheduling-conflicts-and-absences) for the university's policies around missing a final exam. If you miss our Final Exam due to an illness or similar documented with a Dean’s Excuse, you will receive an Incomplete and can take the final exam later.
:::

::: callout-note
## Grace
For students who take all exams (Midterm 1, Midterm 2, and Final Exam), the final exam score will replace the lower of the two mid-semester exam scores, if the final exam score is higher.
:::







